### ISSUE TITLE
App crash after taking a picture

### ISSUE THREAD

**Issue by thomasporro** [PrandiniUniPD/OCRCamera#31]
After taking a picture, while showing the "Processing window" the app crash.
Here the Error:
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: unipd.se18.ocrcamera, PID: 10303
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6648)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:976)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5084)
        at android.view.View.invalidateInternal(View.java:12743)
        at android.view.View.invalidate(View.java:12707)
        at android.view.View.invalidate(View.java:12691)
        at android.widget.TextView.checkForRelayout(TextView.java:7160)
        at android.widget.TextView.setText(TextView.java:4357)
        at android.widget.TextView.setText(TextView.java:4214)
        at android.widget.TextView.setText(TextView.java:4189)
        at unipd.se18.ocrcamera.ResultActivity$AsyncLoad.doInBackground(ResultActivity.java:143)
        at unipd.se18.ocrcamera.ResultActivity$AsyncLoad.doInBackground(ResultActivity.java:121)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by PrandiniUniPD** [comment]
Which version of the app are you referring to?

**Comment by thomasporro** [comment]
photo_testing branch

**Comment by PrandiniUniPD** [comment]
In the version where you has returned this crash there are some statement of the UI that not run on the UI thread and launch this exeption (in this case ResultActivity.java:143 but also in ResultActivity.java:141).
In the actual version of the app contained in the CommonDemo branch this bug it should be solved.
So you could update photo_testing with a merging of the update of the last CommonDemo version (merging from CommonDemo into photo_testing) or you could run on the UI Thread these statements.

**Comment by PrandiniUniPD** [comment]
Then if your problem is resolved close this issue.
